updating rawdata-downloader integration

diff --git a/src/rawdata-procedures/src/rawdata-procedures b/src/rawdata-procedures/src/rawdata-procedures
--- a/src/rawdata-procedures/src/rawdata-procedures
+++ b/src/rawdata-procedures/src/rawdata-procedures
@@ -99,16 +99,23 @@ if [ -n "$SWITCH_DOWNLOAD" ]; then
         # Run procedure #
         echo "rawdata-procedures : downloading raw data ..."
         RETURN=$(rawdata-downloader $PARAM_MOUNT/camera/ )
-        EXIT_CODE=$?
-        [ $EXIT_CODE -ne 0 ] && exit 1
+        STATUS=$?
 
-        # Temporary #
-        #RETURN="AA:BB:CC:DD:EE:FF 123768762"
+        # Check procedure status #
+        if [ $STATU -e 0 ]; then
 
-        # Extract returned value - MAC address and master timestamp #
-        ARRAY=($RETURN)
-        PARAM_MAC=${ARRAY[0]}
-        PARAM_MASTER=${ARRAY[1]}
+            # Extract returned value - MAC address and master timestamp #
+            ARRAY=($RETURN)
+            PARAM_MAC=${ARRAY[0]}
+            PARAM_MASTER=${ARRAY[1]}
+
+        else
+
+            # Exit script #
+            echo "Error : rawdata-downloader fail to proceed"
+            exit 1
+
+        fi
 
     else 
 
