updating rawdata-downloader tools (wip)

diff --git a/src/rawdata-downloader/src/bin/build-modules-file b/src/rawdata-downloader/src/bin/build-modules-file
--- a/src/rawdata-downloader/src/bin/build-modules-file
+++ b/src/rawdata-downloader/src/bin/build-modules-file
@@ -37,67 +37,51 @@
 
 #set -e
 
-export SCRIPT=$(basename $0)
+. $(dirname $0)/rawdata-toolbox.sh
 
-if [ $UID -ne 0 ] ; then
-  echo error: $(basename $0) must be run as root
-  exit 1
-fi
+assertroot
 
-HOTSWAP_USING_SYS=yes
-BASE_IP=192.168.0
-MASTER_IP=221
-N=9
+init() {
+  export HOTSWAP_USING_SYS=yes
+  export BASE_IP=192.168.0
+  export MASTER_IP=221
+  export MODULES_COUNT=9
+  export MUXES=(192.168.0.224 192.168.0.228)
+  export MUX_MAX_INDEX=(4 5)
+  export SPOOL=/var/spool/rawdata-downloader
 
-MUXES=(192.168.0.224 192.168.0.228)
-MUX_MAX_INDEX=(4 5)
+  [ -f /etc/defaults/rawdata-downloader ] && . /etc/defaults/rawdata-downloader
 
-SPOOL=/var/spool/rawdata-downloader
-
-[ -f /etc/defaults/rawdata-downloader ] && . /etc/defaults/rawdata-downloader
-
-mkdir -p $SPOOL || exit 1
-[ -n "$DEBUG" ] && set -x && set -v
-export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-
-trap "killtree -9 $MYPID yes" EXIT SIGINT SIGKILL SIGTERM SIGHUP
-
-# remove scsi host (will be added in connect_q_run after requesting connection for next ssd of this mux)
-remove_scsi_device() {
-  [ -n "REMOVE_SCSI_DEVICE" ] || return
-  if [ -n "$HOTSWAP_USING_SYS" ] ; then
-    log ${LINENO} set device $DEVICE  offline and delete it
-    echo offline | tee /sys/block/$(basename $DEVICE)/device/state 2>&1 | logstdout ${LINENO}
-    echo 1 | tee /sys/block/$(basename $DEVICE)/device/delete 2>&1 | logstdout ${LINENO}
-  else
-    log ${LINENO} removing device mux $MUX_INDEX index $REMOTE_SSD_INDEX
-    echo "scsi remove-single-device $SCSIHOST" | tee /proc/scsi/scsi 2>&1 | logstdout ${LINENO}
+  # parse command line options
+  if ! options=$(getopt -o hm:I:i:vdp -l help,mountpoint:,baseip:,masterip:,verbose,debug,proc -- "$@")
+  then
+      # something went wrong, getopt will put out an error message for us
+      exit 1
   fi
-  echo $SCSIHOST >> $REMOVED_SCSI_TMP
-}
 
-# add scsi device, if previously removed after previous ssd backup for this mux
-add_scsi_device() {
-  [ -n "REMOVE_SCSI_DEVICE" ] || return
-  hbtl=$(get_scsihost $MUX_INDEX)
-  if [ -n "$hbtl" ] ; then
-    log ${LINENO} "adding scsi device using values from cache"
-    if [ -n "$HOTSWAP_USING_SYS" ] ; then
-      hbtl=($hbtl)
-      echo "${hbtl[1]} ${hbtl[2]} ${hbtl[3]}" | tee /sys/class/scsi_host/host${hbtl[0]}/scan 2>&1 | logstdout ${LINENO}
-    else
-      echo "scsi add-single-device $hbtl" | tee /proc/scsi/scsi 2>&1 | logstdout ${LINENO}
-    fi
-  fi
-}
+  eval set -- "$options"
 
-# wait udev generated files in spool folder before mounting disk and launching backup in background
-assertcommands() {
-  while [ $# -ne 0 ] ; do
-    local CMD=$1
-    shift
-    [ -z "$(which $CMD)" ] && echo command $CMD not found && exit 1
+  while [ $# -gt 0 ] ; do
+      case $1 in
+      -h|--help) usage $1 ;;
+      -m|--mountpoint) MOUNTPOINT=$2 ; shift ;;
+      -I|--baseip) BASE_IP=$2 ; shift ;;
+      -i|--masterip) MASTER_IP=$2 ; shift ;;
+      -v|--verbose) VERBOSE=-v ;;
+      -d|--debug) DEBUG=-d ;;
+      -p|--proc) HOTSWAP_USING_SYS= ;;
+      (--) shift; break;;
+      (-*) echo "$(basename $0): error - unrecognized option $1" 1>&2; exit 1;;
+      (*) break;;
+      esac
+      shift
   done
+  mkdir -p $SPOOL || exit 1
+
+  debugmode_update
+  get_camera_macaddr
+  checkdependencies
+
 }
 
 checkdependencies() {
@@ -109,105 +93,17 @@ checkdependencies() {
 }
 
 usage() {
-  echo "usage: $(basename $0) <destination>"
+  echo "$(basename $0) <destination>"
   exit $1
 }
 
-# kill child processes, and optionally the root process
-killtree() {
-    trap '' SIGINT
-    local _pid=$2
-    local _sig=$1
-    local killroot=$3
-
-    # stop parents children production between child killing and parent killing
-    #[ "${_pid}" != "$MYPID" ] && kill -STOP ${_pid}
-    for _child in $(ps -o pid --no-headers --ppid ${_pid} 2>/dev/null); do
-        killtree ${_sig} ${_child} yes
-    done
-    [ -n "$killroot" ] && kill ${_sig} ${_pid} 2>/dev/null
-}
-
-macaddr() {
-  _ADDR=$1
-  arp -n $_ADDR | awk '/[0-9a-f]+:/{gsub(":","-",$3);print $3}'
-}
-
-umount_cf() {
-  HOSTS=$USER_AT_HOST sshall << 'EOF'
-if grep -q ' /usr/html/CF ' /proc/mounts ; then
-  sync
-  umount /usr/html/CF || exit 1
-  sync
-fi
-exit 0
-EOF
-}
-
-get_remote_disk_serial() {
-  HOSTS=$USER_AT_HOST sshall /sbin/hdparm -i $1 \| sed -r -n -e "'s/.*SerialNo=([^ ]+).*/\1/p'"
-}
-
-get_hbtl() {
-  grep DEVPATH= $1 | sed -r -n -e 's#.*/([0-9]:[0-9]:[0-9]:[0-9])/.*#\1#' -e T -e 's/:/ /gp'
-}
-
-log() {
-  echo $(date +%F_%r) $SCRIPT $BASHPID $@ >&2
-}
-
-# format stdin for logginG
-logstdout() {
-  while read l ; do
-    echo $(date +%F_%R:%S) $SCRIPT $BASHPID $@ $l >&2
-  done
-}
-
-# return array index of serial
-get_ssd_index() {
-  _SERIAL=$1
-  for (( i=0 ; $i < ${#SSD_SERIAL[@]} ; ++i )) ; do
-    if [ "${SSD_SERIAL[$i]}" = "$_SERIAL" ] ; then
-      echo $i
-      break
-    fi
-  done
-}
-
-modtime() {
-  expr $(date +%s) - $(stat -c %Y "$1")
-}
-
-get_camera_uptime() {
-  ssh root@$BASE_IP.$MASTER_IP cat /proc/uptime | cut -f 1 -d '.'
-}
-
-# cache scsi address associated with mux index
-save_scsihost() {
-  MUX_INDEX=$1
-  shift
-  SCSIHOST=$@
-  grep -q $MUX_INDEX $SCSIHOST_TMP || echo $MUX_INDEX $SCSIHOST >> $SCSIHOST_TMP
-}
-
-# read cached scsi address associated with mux index
-get_scsihost() {
-  MUX_INDEX=$1
-  grep $MUX_INDEX $SCSIHOST_TMP | sed -r -e 's/^[0-9]+ (.*)/\1/'
-}
-
-# get module number for ssd serial
-get_module_index() {
-  local SERIAL=$1
-  echo $(($(get_ssd_index $SERIAL)+1))
-}
-
+# add "<module_index> <mux_index> <ssd_index> <ssd_serial>" entry to MODULES_FILE
 save_module_address() {
   local MUX_INDEX=$1
   local REMOTE_SSD_INDEX=$2
-  local SERIAL=$3
-  grep -q -E -e " $SERIAL\$" $MODULES_FILE && return 0
-  echo $(get_module_index $SERIAL) $MUX_INDEX $REMOTE_SSD_INDEX $SERIAL >> $MODULES_FILE
+  local SSD_SERIAL=$3
+  grep -q -E -e " $SSD_SERIAL\$" $MODULES_FILE && return 0
+  echo $(get_module_index $SSD_SERIAL) $MUX_INDEX $REMOTE_SSD_INDEX $SSD_SERIAL >> $MODULES_FILE
   MODULES_FILE_TMP=/tmp/$(basename $MODULES_FILE).$$
   sort -u $MODULES_FILE > $MODULES_FILE_TMP
   cat $MODULES_FILE_TMP > $MODULES_FILE
@@ -218,50 +114,60 @@ save_module_address() {
 check_module_address() {
   local MUX_INDEX=$1
   local REMOTE_SSD_INDEX=$2
-  local SERIAL=$3
+  local SSD_SERIAL=$3
   # ignore if not in modules file
   grep -q -E -e "^[0-9]+ $MUX_INDEX $REMOTE_SSD_INDEX " $MODULES_FILE || return 0
   # return error if serial is not matching saved one for mux/ssd pair
-  grep -q -E -e " $MUX_INDEX $REMOTE_SSD_INDEX $SERIAL\$" $MODULES_FILE
+  grep -q -E -e " $MUX_INDEX $REMOTE_SSD_INDEX $SSD_SERIAL\$" $MODULES_FILE
 }
 
-# wait udev generated files in spool folder before mounting disk and save module address in background
+# wait udev generated files in spool folder, then validate and save module address
 wait_and_register() {
 
   log ${LINENO} "<= wait_and_register"
 
-  inotifywait -m -e close_write $SPOOL | while read l ; do
+  local FIFO=$(mktmp -u).$$
+  mkfifo $FIFO
+  inotifywait -m -e close_write $SPOOL > $FIFO 2>&1
+  local INOTIFY_PID=$!
+
+  local l
+  while read l ; do
 
     log ${LINENO} INOTIFY $SPOOL $l
 
+    local event=($l)
+
+    # 1st string from inotifywait is not $SPOOL then it is from stderr
+    [ "${event[0]}" != "$SPOOl" ] && continue
+
     # second string returned by inotifywait is filename (disk serial)
-    event=($l)
-    SERIAL=${event[2]}
+    local SSD_SERIAL=${event[2]}
 
     # get spool filename
-    UDEVINFO=$SPOOL/${event[2]}
+    local UDEVINFO=$SPOOL/${event[2]}
 
     # get scsi host from spool filename
-    SCSIHOST=$(get_hbtl $UDEVINFO)
+    local SCSIHOST=$(get_hbtl $UDEVINFO)
     [ -z "$SCSIHOST" ] && killtree -KILL $MYPID
 
     # get saved connecting disk info
-    DISK_CONNECTING_INFO=($(cat $DISK_CONNECTING_TMP))
-    MUX_INDEX=${DISK_CONNECTING_INFO[0]}
-    REMOTE_SSD_INDEX=${DISK_CONNECTING_INFO[1]}
-    ISRETRY=${DISK_CONNECTING_INFO[2]}
-    DEVICE=$(grep DEVNAME "$UDEVINFO" | cut -f 2 -d '=')
+    local DISK_CONNECTING_INFO=($(cat $DISK_CONNECTING_TMP))
+    local MUX_INDEX=${DISK_CONNECTING_INFO[0]}
+    local REMOTE_SSD_INDEX=${DISK_CONNECTING_INFO[1]}
+    local ISRETRY=${DISK_CONNECTING_INFO[2]}
+    local DEVICE=$(grep DEVNAME "$UDEVINFO" | cut -f 2 -d '=')
 
-    log ${LINENO} device_connected $MUX_INDEX $REMOTE_SSD_INDEX $SCSIHOST $SERIAL $DEVICE
+    log ${LINENO} device_connected $MUX_INDEX $REMOTE_SSD_INDEX $SCSIHOST $SSD_SERIAL $DEVICE
 
     # assert previously saved module address match the connecting disk
-    if ! check_module_address $MUX_INDEX $REMOTE_SSD_INDEX $SERIAL 2>&1 | logstdout ${LINENO} ; then
-      log ${LINENO} invalid_address "saved serial for mux $MUX_INDEX ssd $REMOTE_SSD_INDEX is not matching  $SERIAL"
+    if ! check_module_address $MUX_INDEX $REMOTE_SSD_INDEX $SSD_SERIAL 2>&1 | logstdout ${LINENO} ; then
+      log ${LINENO} invalid_address "saved serial for mux $MUX_INDEX ssd $REMOTE_SSD_INDEX is not matching $SSD_SERIAL"
       killtree -KILL $MYPID
     fi
 
     # cache camera module address (mux index, ssd index)
-    save_module_address $MUX_INDEX $REMOTE_SSD_INDEX $SERIAL 2>&1 | logstdout ${LINENO}
+    save_module_address $MUX_INDEX $REMOTE_SSD_INDEX $SSD_SERIAL 2>&1 | logstdout ${LINENO}
 
     # cache mux index and scsi host association
     save_scsihost $MUX_INDEX $SCSIHOST
@@ -274,25 +180,27 @@ wait_and_register() {
 
     # set already connected flag
     touch $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connected || killtree -KILL $MYPID
-    echo $SCSIHOST $SERIAL $DEVICE > $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connected
+    echo $SCSIHOST $SSD_SERIAL $DEVICE > $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connected
 
-    enqueue_next_ssd $MUX_INDEX $REMOTE_SSD_INDEX $SCSIHOST $SERIAL $DEVICE $ISRETRY &
+    enqueue_next_ssd $MUX_INDEX $REMOTE_SSD_INDEX $SCSIHOST $SSD_SERIAL $DEVICE $ISRETRY &
 
-  done
+  done < $FIFO
+
+  kill -TERM $INOTIFY_PID > /dev/null 2>&1 
 }
 
 # enqueue next ssd for this mux
 enqueue_next_ssd() {
-  MUX_INDEX=$1
-  REMOTE_SSD_INDEX=$2
-  SCSIHOST="$3 $4 $5 $6"
-  SERIAL=$7
-  DEVICE=$8
-  ISRETRY=$9
+  local MUX_INDEX=$1
+  local REMOTE_SSD_INDEX=$2
+  local SCSIHOST="$3 $4 $5 $6"
+  local SSD_SERIAL=$7
+  local DEVICE=$8
+  local ISRETRY=$9
 
-  # quit if already registered - should not happend
-  if [ -f $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_registered ] ; then
-    log ${LINENO} already registered
+  # quit if already processed - should not happend
+  if [ -f $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_processed ] ; then
+    log ${LINENO} already processed
     killtree -KILL $MYPID
   fi
 
@@ -305,38 +213,49 @@ enqueue_next_ssd() {
   # remove flag
   rm $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connected || killtree -KILL $MYPID
 
-  # set registered flag
-  touch $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_registered || killtree -KILL $MYPID
-  echo $SCSIHOST $SERIAL $DEVICE $STATUS > $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_registered
+  # set processed flag
+  touch $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_processed || killtree -KILL $MYPID
+  echo $SCSIHOST $SSD_SERIAL $DEVICE $STATUS > $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_processed
 
-  echo $SERIAL >> $SERIAL_DONE_TMP
+  # add serial to processed list
+  echo $SSD_SERIAL >> $SSD_SERIAL_DONE_TMP
+
   # show progression
-  SERIAL_DONE_COUNT=$(sort -u $SERIAL_DONE_TMP | wc -l)
-  log ${LINENO} registration_done_count $SERIAL_DONE_COUNT
+  local SSD_SERIAL_DONE_COUNT=$(sort -u $SSD_SERIAL_DONE_TMP | wc -l)
+  log ${LINENO} registration_done_count $SSD_SERIAL_DONE_COUNT
 
   # enqueue this mux's next ssd for backup (ignore this step for retries)
   if [ "$ISRETRY" = "" -a $REMOTE_SSD_INDEX -lt ${MUX_MAX_INDEX[$MUX_INDEX]} ] ; then
     log ${LINENO} enqueue mux $MUX_INDEX ssd $((REMOTE_SSD_INDEX+1))
     echo $MUX_INDEX $((REMOTE_SSD_INDEX+1)) >> $CONNECT_Q_TMP
+
   else
-    # check mux done
+    # it is a retry or MUX_MAX_INDEX has been reached
     if ! is_any_ssd_left_in_queue_for_mux $MUX_INDEX ; then
       MUX_DONE=$(cat $MUX_DONE_TMP)
       echo $((++MUX_DONE)) > $MUX_DONE_TMP
     fi
     log ${LINENO} mux_done_count $MUX_DONE
+
   fi
 
-  # exit when nothing left to do
+  # exit when all muxes have been processed
   if [ "$MUX_DONE" = "${#MUXES[@]}" ] ; then
-    if [ $(sort -u $SERIAL_DONE_TMP | wc -l) -eq $N ] ; then
+
+    if [ $(sort -u $SSD_SERIAL_DONE_TMP | wc -l) -eq $MODULES_COUNT ] ; then
+      log "${LINENO} SUCCESS - all modules processed successfuly"
       log ${LINENO} exit_status 0
       echo 0 > $EXIT_CODE_TMP
+
     else
+      log "${LINENO} FAILURE - some modules could not be processed"
       log ${LINENO} exit_status 1
       echo 1 > $EXIT_CODE_TMP
+
     fi
+
     killtree -KILL $MYPID
+
   fi
 }
 
@@ -344,26 +263,6 @@ is_any_ssd_left_in_queue_for_mux() {
    export MUX_INDEX=$1
    QSEQ=$(cat $QSEQ_TMP)
    tail -n +$(($QSEQ+1)) $CONNECT_Q_TMP | cut -f 1 -d ' ' | grep -q -e '^'$MUX_INDEX'$'
-}
-
-wait_watches_established() {
-
-  local INOTIFY_STDERR=$1
-  local msg
-
-  FIFO=$(mktemp -u).$$
-  mkfifo $FIFO
-  tail -f $INOTIFY_STDERR > $FIFO 2>&1 &
-  TAIL_PID=$!
-
-  while read msg ; do
-    echo $msg | logstdout ${LINENO}
-    [[ "$msg" =~ "Watches established" ]] && break
-  done < $FIFO
-
-  kill $TAIL_PID > /dev/null 2>&1
-
-  rm $INOTIFY_STDERR $FIFO
 }
 
 # switch esata connections sequentially reading from $CONNECT_Q_TMP
@@ -404,7 +303,7 @@ connect_q_run() {
       INOTIFY_STDERR=$(mktemp)
       timeout -k 10 30 inotifywait -e close_write $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connecting > /dev/null 2> $INOTIFY_STDERR &
       TIMEOUTPID=$!
-      wait_watches_established $INOTIFY_STDERR 2>&1 | grep -v -e INOTIFY_STDERR | logstdout ${LINENO}
+      wait_regexp $INOTIFY_STDERR "Watches established" 2>&1 | grep -v -e INOTIFY_STDERR | logstdout ${LINENO}
 
       # before requesting disk connection, save connecting disk info
       echo $MUX_INDEX $REMOTE_SSD_INDEX $ISRETRY > $DISK_CONNECTING_TMP
@@ -446,65 +345,22 @@ connect_q_run() {
   rm $FIFO
 }
 
-# reset multiplexers
-reset_eyesis_ide() {
-  log ${LINENO} reset eyesis_ide
-  for (( i=0 ; $i < ${#MUXES[@]} ; ++i )) do
-    log ${LINENO} wget http://${MUXES[$i]}/eyesis_ide.php
-    wget -q http://${MUXES[$i]}/eyesis_ide.php -O - > /dev/null || exit 1
-  done
-}
-
-# unmount ssd on cameras
-umount_all() {
-  STATUS=()
-  umount_cf 2>&1 | tee | while read l ; do
-    msg=($l)
-    [ ${msg[0]} = "sshall:" ] || continue
-    LOGIN=${msg[1]}
-    [ -z "$LOGIN" ] && echo umount_all: $l && killtree -KILL $MYPID
-    WHAT=${msg[2]}
-    [ "$WHAT" != "status" ] && continue
-    IP=$(echo $LOGIN | sed -r -n -e 's/.*@[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+).*/\1/p')
-    INDEX=$(expr $IP - $MASTER_IP)
-    STATUS[$INDEX]=${msg[3]}
-    [ "${STATUS[$INDEX]}" != "0" ] && echo umount_cf $IP && killtree -KILL $MYPID
-  done
-}
-
 ########### main script
 
 SCSIHOST=()
 
-[ -z "$DESTINATION" ] && DESTINATION=$1
+[ -z "$DESTINATION" ] && DESTINATION=$1 && shift
 
-if [ -z "$DESTINATION" ] ; then
+if [ -z "$DESTINATION" -o "$#" -gt 0 ] ; then
   usage 1
 fi
 
-for opt in $@ ; do
-  [ "$opt" = "-h" ] && usage 0
-done
-
 checkdependencies
-
-# get camera master ip mac address
-if ! ping -w 5 -c 1 $BASE_IP.$MASTER_IP > /dev/null ; then
-  log ${LINENO} unable to ping $BASE_IP.$MASTER_IP
-  exit 1
-fi
-
-MACADDR=$(macaddr $BASE_IP.$MASTER_IP)
-if [ -z "$MACADDR" ] ; then
-  log ${LINENO} unable to get MAC address for $BASE_IP.$MASTER_IP
-  exit 1
-fi
 
 TMP=/tmp/rawdata-downloader/$MACADDR/$$
 mkdir -p $TMP
 
 # create shared variables and inter-process storage
-export MYPID=$BASHPID
 export EXIT_CODE_TMP=$(mktemp --tmpdir=$TMP)
 export DISK_CONNECTING_TMP=$(mktemp --tmpdir=$TMP)
 export SSD_SERIAL_TMP=$(mktemp --tmpdir=$TMP)
@@ -512,7 +368,7 @@ export REMOVED_DEVICES=$(mktemp --tmpdir=$TMP)
 export CONNECT_Q_TMP=$(mktemp --tmpdir=$TMP)
 export MUX_DONE_TMP=$(mktemp --tmpdir=$TMP)
 export QSEQ_TMP=$(mktemp --tmpdir=$TMP)
-export SERIAL_DONE_TMP=$(mktemp --tmpdir=$TMP)
+export SSD_SERIAL_DONE_TMP=$(mktemp --tmpdir=$TMP)
 export REMOVED_SCSI_TMP=$TMP/../removed_scsi
 
 echo 1 > $EXIT_CODE_TMP
@@ -520,17 +376,7 @@ echo 0 > $QSEQ_TMP
 echo 0 > $MUX_DONE_TMP
 touch $REMOVED_SCSI_TMP
 
-log ${LINENO} get camera uptime
-CAMERA_UPTIME=$(get_camera_uptime)
-if [ -z "$CAMERA_UPTIME" ] ; then
-  log ${LINENO} cannot get camera uptime
-  exit 1
-fi
-
-if [ $CAMERA_UPTIME -lt 120 ] ; then
-  log ${LINENO} wait $((120-CAMERA_UPTIME)) seconds for camera wake up
-  sleep $((120-CAMERA_UPTIME))
-fi
+wait_until_camera_awake
 
 # clear scsi hosts cache if modification time older than camera uptime
 export SCSIHOST_TMP=$TMP/../scsihosts
@@ -548,56 +394,24 @@ DEST="$DESTINATION/$(echo $MACADDR | tr 'a-f' 'A-F')"
 mkdir -p "$DEST/info/rawdata-downloader" || exit 1
 export MODULES_FILE="$DEST/info/rawdata-downloader/modules"
 
-# build sshall login list
-for (( i=0 ; $i < $N ; ++i )) ; do
-  USER_AT_HOST="$USER_AT_HOST "root@$BASE_IP.$((MASTER_IP + i))
-done
+build_sshall_login_list $MODULES_COUNT
 
-# get camera ssd serials
-STATUS=()
-log ${LINENO} get ssd serials
-export SSD_SERIAL=()
-get_remote_disk_serial /dev/hda 2>&1 | while read l ; do
-  msg=($l)
-  [ ${msg[0]} = "sshall:" ] || continue
-  [ ${msg[2]} = "stderr" ] && log ${LINENO} get_remote_disk_serial: $l
-  LOGIN=${msg[1]}
-  [ -z "$LOGIN" ] && log ${LINENO} get_remote_disk_serial: $l && killtree -KILL $MYPID
-  IP=$(echo $LOGIN | sed -r -n -e 's/.*@[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+).*/\1/p')
-  INDEX=$(expr $IP - $MASTER_IP)
-  WHAT=${msg[2]}
-  case "$WHAT" in
-  status)
-    STATUS[$INDEX]=${msg[3]}
-    [ "${STATUS[$INDEX]}" != "0" ] && log ${LINENO} get_remote_serial: $IP && killtree -KILL $MYPID
-    ;;
-  stdout)
-    SERIAL=${msg[3]}
-    echo SSD_SERIAL[$INDEX]=$SERIAL >> $SSD_SERIAL_TMP
-    ;;
-  esac
-done
-
-cat $SSD_SERIAL_TMP | logstdout ${LINENO}
-. $SSD_SERIAL_TMP
+get_camera_ssd_serials
 
 log ${LINENO} got ${#SSD_SERIAL[@]} SSD serials
 
-[ ${#SSD_SERIAL[@]} -ne $N ] && exit 1
+[ ${#SSD_SERIAL[@]} -ne $MODULES_COUNT ] && exit 1
 
 rm $SSD_SERIAL_TMP
 
 # unmount camera ssd
 log ${LINENO} umount CF
-umount_all
+umount_all 2>&1 | logstdout ${LINENO}
 
-# run backgroud task waiting for disks and launching backups
+# wait for disks and register modules in background
 wait_and_register &
 
-# queue first ssd for each mux
-for (( i=0 ; i < ${#MUXES[@]} ; ++i )) ; do
-  echo $i 1 >> $CONNECT_Q_TMP
-done
+connect_queue_init
 
 # run queue in background
 log ${LINENO} starting queue processing
@@ -613,21 +427,14 @@ trap '' SIGINT
 log ${LINENO} resetting multiplexers
 reset_eyesis_ide
 
-# add previously removed scsi devices
-if [ -z "$HOTSWAP_USING_SYS" ] ; then
-  sort -u $REMOVED_SCSI_TMP | while read hbtl ; do
-    log ${LINENO} "adding previously removed scsi devices"
-    echo "scsi add-single-device $hbtl" | tee /proc/scsi/scsi 2>&1 | logstdout ${LINENO}
-    sed -r -i -e "/^$hbtl\$/d" $REMOVED_SCSI_TMP
-  done
-fi
+restore_scsi_devices
 
 EXIT_CODE=$(cat $EXIT_CODE_TMP)
 
 [ $EXIT_CODE -eq 0 ] && echo $MODULES_FILE
 
 # remove temporary files
-rm $TMP/$$ -r 2> /dev/null
+rm $TMP -r 2> /dev/null
 
 log ${LINENO} exit $EXIT_CODE
 exit $EXIT_CODE
