rawdata-downloader: error messages on non verbose mode

diff --git a/src/rawdata-downloader/src/bin/connect-module b/src/rawdata-downloader/src/bin/connect-module
--- a/src/rawdata-downloader/src/bin/connect-module
+++ b/src/rawdata-downloader/src/bin/connect-module
@@ -93,14 +93,14 @@ init() {
 
     # get camera master ip mac address
     if ! ping -w 5 -c 1 $BASE_IP.$MASTER_IP > /dev/null ; then
-      log ${LINENO} unable to ping $BASE_IP.$MASTER_IP
+      log ${LINENO} error: unable to ping $BASE_IP.$MASTER_IP
       exit 1
     fi
 
     MACADDR=$(macaddr $BASE_IP.$MASTER_IP | tr 'a-f' 'A-F')
 
     if [ -z "$MACADDR" ] ; then
-      log ${LINENO} "unable to get MAC address for $BASE_IP.$MASTER_IP"
+      log ${LINENO} error: "unable to get MAC address for $BASE_IP.$MASTER_IP"
       exit 1
     fi
 
@@ -110,8 +110,8 @@ init() {
   # check modules file exist
   MODULES_FILE=$MOUNTPOINT/camera/$MACADDR/rawdata-downloader/modules
   if [ ! -f $MODULES_FILE ] ; then
-    log ${LINENO} error file not found: $MODULES_FILE
-    log ${LINENO} "specify the proper mount point with -m or run 'build-modules-file $MOUNTPOINT' first"
+    log ${LINENO} error: file not found: $MODULES_FILE
+    log ${LINENO} error: "specify the proper mount point with -m or run 'build-modules-file $MOUNTPOINT' first"
     exit 1
   fi
 
@@ -197,7 +197,7 @@ check_module_address() {
 # wait udev generated file in spool folder for requested module device  before exiting
 wait_and_exit() {
 
-  log ${LINENO} "<= wait_and_exit"
+  log ${LINENO} error: "<= wait_and_exit"
 
   # use FIFO instead of PIPE, to exit loop smoothly and avoid messing with environment variables
   local FIFO=$(mktemp -u).$$
@@ -206,7 +206,7 @@ wait_and_exit() {
   local INOTIFY_PID=$!
  
   while read l ; do
-    log ${LINENO} $SPOOL INOTIFY $l
+    log ${LINENO} debug: $SPOOL INOTIFY $l
 
     # second string returned by inotifywait is filename (disk serial)
     event=($l)
@@ -226,9 +226,9 @@ wait_and_exit() {
     ISRETRY=${DISK_CONNECTING_INFO[2]}
     DEVICE=$(grep DEVNAME "$UDEVINFO" | cut -f 2 -d '=')
 
-    log ${LINENO} device_connected $_MUX_INDEX $_REMOTE_SSD_INDEX $SCSIHOST $SERIAL $DEVICE
+    log ${LINENO} info: device_connected $_MUX_INDEX $_REMOTE_SSD_INDEX $SCSIHOST $SERIAL $DEVICE
 
-    log ${LINENO} unpause connect queue         
+    log ${LINENO} info: unpause connect queue         
     touch $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connecting || killtree -KILL $MYPID                                   
 
     [ "$_MUX_INDEX" != "$MUX_INDEX" ] && continue
@@ -236,7 +236,7 @@ wait_and_exit() {
 
     # assert previously saved module address match the connecting disk
     if ! check_module_address $_MUX_INDEX $_REMOTE_SSD_INDEX $SERIAL 2>&1 | logstdout ${LINENO} ; then
-      log ${LINENO} invalid_address "saved serial for mux $MUX_INDEX ssd $REMOTE_SSD_INDEX is not matching  $SERIAL"
+      log ${LINENO} error: invalid_address "saved serial for mux $MUX_INDEX ssd $REMOTE_SSD_INDEX is not matching  $SERIAL"
 
     else
       # success
@@ -284,7 +284,7 @@ request_ssd() {
     REMOTE_SSD_INDEX=$REMOTE_SSD_INDEX
     ISRETRY=
 
-    log ${LINENO} going to request mux $MUX_INDEX ssd $REMOTE_SSD_INDEX
+    log ${LINENO} info: going to request mux $MUX_INDEX ssd $REMOTE_SSD_INDEX
 
     while true ; do
 
@@ -300,16 +300,16 @@ request_ssd() {
       echo $MUX_INDEX $REMOTE_SSD_INDEX $ISRETRY > $DISK_CONNECTING_TMP
 
       # request disk connection
-      log ${LINENO} requesting sata disk mux $MUX_INDEX index $REMOTE_SSD_INDEX
-      log ${LINENO} wget http://${MUXES[$MUX_INDEX]}/103697.php?c:host4=ssd$REMOTE_SSD_INDEX
+      log ${LINENO} info: requesting sata disk mux $MUX_INDEX index $REMOTE_SSD_INDEX
+      log ${LINENO} info: wget http://${MUXES[$MUX_INDEX]}/103697.php?c:host4=ssd$REMOTE_SSD_INDEX
       wget -q http://${MUXES[$MUX_INDEX]}/103697.php?c:host4=ssd$REMOTE_SSD_INDEX -O - > /dev/null || killtree -KILL $MYPID
 
       # wait for inotifywait and timeout setup above
-      log ${LINENO} waiting for mux $MUX_INDEX disk $REMOTE_SSD_INDEX
+      log ${LINENO} info: waiting for mux $MUX_INDEX disk $REMOTE_SSD_INDEX
       wait $TIMEOUTPID 2> /dev/null
       timeout_status=$?
 
-      log ${LINENO} timeout "status $timeout_status wating for mux $MUX_INDEX disk $REMOTE_SSD_INDEX"
+      log ${LINENO} debug: timeout "status $timeout_status wating for mux $MUX_INDEX disk $REMOTE_SSD_INDEX"
 
       rm $TMP/${MUX_INDEX}_${REMOTE_SSD_INDEX}_connecting
 
@@ -353,16 +353,16 @@ SCSIHOST_TMP=$TMP/../scsihosts
 
 if [ -z "$NO_CHECKLIST" ] ; then
 
-  log ${LINENO} get camera uptime
+  log ${LINENO} info: get camera uptime
   CAMERA_UPTIME=$(get_camera_uptime)
   if [ -z "$CAMERA_UPTIME" ] ; then
-    log ${LINENO} cannot get camera uptime
+    log ${LINENO} error: cannot get camera uptime
     exit 1
   fi
 
-  if [ $CAMERA_UPTIME -lt 120 ] ; then
-    log ${LINENO} wait $((120-CAMERA_UPTIME)) seconds for camera wake up
-    sleep $((120-CAMERA_UPTIME))
+  if [ $CAMERA_UPTIME -lt 180 ] ; then
+    log ${LINENO} info: wait $((180-CAMERA_UPTIME)) seconds for camera wake up
+    sleep $((180-CAMERA_UPTIME))
   fi
 
   # clear scsi hosts cache if modification time older than camera uptime
@@ -402,7 +402,7 @@ if [ -z "${SSD_SERIAL[$((MODULE-1))]}" ] ; then
   export SSHALL_HOSTS="root@$BASE_IP.$((MASTER_IP + MODULE - 1))"
 
   # get camera ssd serial
-  log ${LINENO} get ssd serial
+  log ${LINENO} info: get ssd serial
   SSD_SERIAL=()
   export SSD_SERIAL_TMP
   export MASTER_IP
@@ -412,12 +412,12 @@ if [ -z "${SSD_SERIAL[$((MODULE-1))]}" ] ; then
   get_remote_disk_serial /dev/hda 2>&1 | while read l ; do
     msg=($l)
     if [ ${msg[0]} != "sshall:" ] ; then
-      log ${LINENO} get_remote_disk_serial: $l
+      log ${LINENO} info: get_remote_disk_serial: $l
       continue
     fi
-    [ ${msg[2]} = "stderr" ] && log ${LINENO} get_remote_disk_serial: $l
+    [ ${msg[2]} = "stderr" ] && log ${LINENO} error: get_remote_disk_serial: $l
     LOGIN=${msg[1]}
-    [ -z "$LOGIN" ] && log ${LINENO} get_remote_disk_serial: $l && killtree -KILL $MYPID
+    [ -z "$LOGIN" ] && log ${LINENO} error: get_remote_disk_serial: $l && killtree -KILL $MYPID
     IP=$(echo $LOGIN | sed -r -n -e 's/.*@[0-9]+\.[0-9]+\.[0-9]+\.([0-9]+).*/\1/p')
     INDEX=$(expr $IP - $MASTER_IP)
     WHAT=${msg[2]}
@@ -450,7 +450,7 @@ if [ "${SSD_SERIAL[$((MODULE-1))]}" != "$SERIAL" ] ; then
 fi
 
 # unmount camera ssd
-log ${LINENO} umount CF
+log ${LINENO} info: umount CF
 umount_all 2>&1 | logstdout ${LINENO}
 
 # module address
@@ -460,7 +460,7 @@ REMOTE_SSD_INDEX=${MODULE_INFO[2]}
 # run backgroud task waiting for disk
 wait_and_exit &
 
-log ${LINENO} starting processing
+log ${LINENO} info: starting processing
 
 # request disk
 request_ssd &
@@ -479,5 +479,5 @@ rm $TMP/$$ -r 2> /dev/null
 # kill zombies
 killtree -KILL $MYPID
 
-log ${LINENO} exit $EXIT_CODE
+log ${LINENO} info: exit $EXIT_CODE
 exit $EXIT_CODE
diff --git a/src/rawdata-downloader/src/bin/process-modules b/src/rawdata-downloader/src/bin/process-modules
--- a/src/rawdata-downloader/src/bin/process-modules
+++ b/src/rawdata-downloader/src/bin/process-modules
@@ -57,7 +57,7 @@ init() {
   [ -f /etc/defaults/rawdata-downloader ] && . /etc/defaults/rawdata-downloader
 
   # parse command line options
-  if ! options=$(getopt -o hm:I:i:vda -l help,mountpoint:,baseip:,masterip:,verbose,debug,all -- "$@")
+  if ! options=$(getopt -o hm:I:i:vdas -l help,mountpoint:,baseip:,masterip:,verbose,debug,all,sequentially -- "$@")
   then
       # something went wrong, getopt will put out an error message for us
       exit 1
@@ -92,14 +92,14 @@ init() {
   # retrieve camera mac address from arp cache
   MACADDR=$(macaddr $BASE_IP.$MASTER_IP | tr 'a-f' 'A-F')
   if [ -z "$MACADDR" ] ; then
-    log ${LINENO} "unable to get MAC address for $BASE_IP.$MASTER_IP"
+    log ${LINENO} error: "unable to get MAC address for $BASE_IP.$MASTER_IP"
     exit 1
   fi
 
   MODULES_FILE=$MOUNTPOINT/camera/$MACADDR/rawdata-downloader/modules
   if ! [ -f "$MODULES_FILE" ] ; then
     log ${LINENO} error: "file not found: $MODULES_FILE"
-    log ${LINENO} "run build-modules-file first or specify the proper mountpoint with -m"
+    log ${LINENO} error: "run build-modules-file first or specify the proper mountpoint with -m"
     exit 1
   fi
 
@@ -117,7 +117,7 @@ init() {
   shift
 
   if [ ! -f "$SCRIPT" ] ; then
-    log ${LINENO} "error: script not found: $SCRIPT"
+    log ${LINENO} error: "script not found: $SCRIPT"
     exit 1
   fi
 
@@ -180,7 +180,7 @@ process_module_list() {
 
   for MODULE in $module_list  ; do
 
-    log ${LINENO} module $MODULE connecting
+    log ${LINENO} info: module $MODULE connecting
 
     # request module to multiplexer and get device path
     DEVICE=$(connect-module $VERBOSE $NOCHECKLIST $MODULE --mountpoint $MOUNTPOINT 2>> $LOGFILE)
@@ -190,13 +190,13 @@ process_module_list() {
       break
     fi
 
-    log ${LINENO}  module $MODULE connecting : success
+    log ${LINENO} info: module $MODULE connecting : success
     # dont lose time with camera checklist before requesting next modules
     NOCHECKLIST=--no-checklist
 
     # if already mounted, try to unmount device
     if mount | grep -q ${DEVICE}1 ; then
-      log ${LINENO} unmount ${DEVICE}1
+      log ${LINENO} info: unmount ${DEVICE}1
       if ! umount ${DEVICE}1 2>/dev/null || umount -f ${DEVICE}1 2>/dev/null ; then
         log ${LINENO} error: "could not unmount ${DEVICE}"
         killtree -KILL $MYPID yes
@@ -205,12 +205,12 @@ process_module_list() {
     fi
 
     # run specified script using "source" so that it can access to everything defined here
-    log ${LINENO} "module $MODULE $SCRIPT"
+    log ${LINENO} info: "module $MODULE $SCRIPT"
     if source $SCRIPT ; then
-      log ${LINENO} "module $MODULE $SCRIPT : success"
+      log ${LINENO} info: "module $MODULE $SCRIPT : success"
       echo "${MODULE}" >> $PROCESSED_LIST
     else
-      log ${LINENO} "error: module $MODULE $SCRIPT : failed"
+      log ${LINENO} error: "module $MODULE $SCRIPT : failed"
       killtree -KILL $MYPID yes
       break
     fi
@@ -256,11 +256,11 @@ main() {
   rm $PROCESSED_LIST
 
   if [ "$MODULES_COUNT" != "$PROCESSED_COUNT" ] ; then
-    log ${LINENO} failed: $PROCESSED_COUNT disks processed $PROCESSED_COUNT
+    log ${LINENO} error: failed: $PROCESSED_COUNT disks processed $PROCESSED_COUNT
     exit 1
   fi
 
-  log ${LINENO} success: $PROCESSED_COUNT disks processed
+  log ${LINENO} info: success: $PROCESSED_COUNT disks processed
   exit 0
 
 }
