Merge and procedures and autoseg case management addition

diff --git a/src/rawdata-autoseg/src/rawdata-autoseg b/src/rawdata-autoseg/src/rawdata-autoseg
--- a/src/rawdata-autoseg/src/rawdata-autoseg
+++ b/src/rawdata-autoseg/src/rawdata-autoseg
@@ -174,56 +174,56 @@ topology() {
 process() {
 
     # Creates CSPS/csps-suite sync-specific directories #
-    >&2 echo "  rawdata-autoseg : creating directories ..."
+    >&2 echo "rawdata-autoseg : creating directories ..."
     mkdir -p $AS_SYNC/csps
     mkdir -p $AS_SYNC/csps/decomposed
     mkdir -p $AS_SYNC/csps/recomposed
     mkdir -p $AS_SYNC/csps/validated
 
     # Perform audit on raw logs-files #
-    >&2 echo "  rawdata-autoseg : audit raw logs-files ..."
+    >&2 echo "rawdata-autoseg : audit raw logs-files ..."
     csps-$(device_detect $AS_MACAD)-audit \
         -p $AS_SYNC/mov/1/ \
          > $AS_SYNC/csps/audit-raw.log
 
     # Perform logs-files decomposition #
-    >&2 echo "  rawdata-autoseg : decomposing logs-files ..."
+    >&2 echo "rawdata-autoseg : decomposing logs-files ..."
     csps-$(device_detect $AS_MACAD)-decompose \
         -r $AS_SYNC/mov/1/ -d $AS_SYNC/csps/decomposed -i 1.0 \
          > $AS_SYNC/csps/logs-decompose.log
 
     # Perform audit on decomposed logs-files #
-    >&2 echo "  rawdata-autoseg : audit decomposed logs-files ..."
+    >&2 echo "rawdata-autoseg : audit decomposed logs-files ..."
     csps-$(device_detect $AS_MACAD)-audit \
         -p $AS_SYNC/csps/decomposed \
          > $AS_SYNC/csps/audit-decompose.log
 
     # Perform logs-files recomposition #
-    >&2 echo "  rawdata-autoseg : recomposing logs-files ..."
+    >&2 echo "rawdata-autoseg : recomposing logs-files ..."
     csps-$(device_detect $AS_MACAD)-recompose \
         -d $AS_SYNC/csps/decomposed -r $AS_SYNC/csps/recomposed -i 1.0 \
          > $AS_SYNC/csps/logs-recompose.log
 
     # Perform audit on recomposed logs-files #
-    >&2 echo "  rawdata-autoseg : audit recomposed logs-files ..."
+    >&2 echo "rawdata-autoseg : audit recomposed logs-files ..."
     csps-$(device_detect $AS_MACAD)-audit \
         -p $AS_SYNC/csps/recomposed \
          > $AS_SYNC/csps/audit-recompose.log
 
     # Perform logs-files validation #
-    >&2 echo "  rawdata-autoseg : validating logs-files ..."
+    >&2 echo "rawdata-autoseg : validating logs-files ..."
     csps-$(device_detect $AS_MACAD)-validate \
         -r $AS_SYNC/csps/recomposed -v $AS_SYNC/csps/validated -i 5.0 \
          > $AS_SYNC/csps/logs-validate.log
 
     # Perform audit on validated logs-files #
-    >&2 echo "  rawdata-autoseg : audit validated logs-files ..."
+    >&2 echo "rawdata-autoseg : audit validated logs-files ..."
     csps-$(device_detect $AS_MACAD)-audit \
         -p $AS_SYNC/csps/validated \
          > $AS_SYNC/csps/audit-validate.log
 
     # Create CSPS/csps-suite segments-specific directories #
-    >&2 echo "  rawdata-autoseg : broadcasting segments ..."
+    >&2 echo "rawdata-autoseg : broadcasting segments ..."
     echo "Segments broadcasting : $AS_MACAD:$AS_TIMES :" \
          > $AS_SYNC/csps/logs-broadcast.log
     mkdir -p $AS_SEGM
@@ -269,7 +269,7 @@ process() {
              > /dev/null
 
         # Logging segments broadcasting #
-        echo "  Broadcast $AS_ENUM segment in $(basename $AS_SEGM/$MTS)" \
+        echo "Broadcast $AS_ENUM segment in $(basename $AS_SEGM/$MTS)" \
              >> $AS_SYNC/csps/logs-broadcast.log
 
     done
@@ -286,7 +286,7 @@ unprocess() {
     if [ -d $AS_SYNC/csps ]; then
 
         # Safe-remove #
-        >&2 echo "  rawdata-autoseg : safe removing sync auto-segmentation directories ..."
+        >&2 echo "rawdata-autoseg : safe removing sync auto-segmentation directories ..."
         rm    --force                    $AS_SYNC/csps/validated/*
         rmdir --ignore-fail-on-non-empty $AS_SYNC/csps/validated
         rm    --force                    $AS_SYNC/csps/recomposed/*
@@ -340,6 +340,7 @@ AS_SEGM=$AS_MOUNT/camera/$AS_MACAD/raw/segment/$AS_TIMES
 if [ ! -d $AS_MOUNT/camera/$AS_MACAD/raw ]; then
 
     # Exit script #
+    >&2 echo "rawdata-autoseg : unable to locate [raw] directory ..."
     exit 1
 
 else
@@ -366,6 +367,11 @@ else
 
         # Process raw data #
         process
+
+    else
+
+        # Skip auto-segmentation #
+        >&2 echo "rawdata-autoseg : nothing to do ..."
 
     fi
 
diff --git a/src/rawdata-procedures/src/rawdata-procedures b/src/rawdata-procedures/src/rawdata-procedures
--- a/src/rawdata-procedures/src/rawdata-procedures
+++ b/src/rawdata-procedures/src/rawdata-procedures
@@ -90,11 +90,20 @@ arguments() {
 # Argument and parameters #
 arguments $@
 
+# Check standard directories #
+if [ ! -d $PARAM_MOUNT/camera ] || [ ! -d $PARAM_MOUNT/footage ]; then
+
+    # Exit script #
+    echo "Error : unable to access standard directory with specified mount point"
+    exit 1
+
+fi
+
 # Check execution consistency #
 if [ -n "$SWITCH_DOWNLOAD" ]; then
 
     # Check execution consistency #
-    if [ -n "$PARAM_MAC" ] || [ -n "$PARAM_MASTER" ]; then
+    if [ -n "$PARAM_MAC" ] || [ -n "$PARAM_MASTER" ] || [ -n "$PARAM_SEGMENT" ]; then
 
         # Exit script #
         echo "Error : unable to understand --download switch with --mac-address/--master-timestamp parameters"
